package com.opensense.dashboard.shared;

public enum MeasurandType {
	TEMPERATURE,NOISE,HUMIDITY,BRIGHTNESS,AIR_PRESSURE,WIND_SPEED,WIND_DIRECTION,CLOUDINESS,PRECIPITATION_AMOUNT,PRECIPITATION_TYPE,PM10,PM2_5;
}
